feat: add quantity tracker functions
gnumi34/golang-mentoring pull request #11
Opened 2022-09-09 11:14 UTC by Asgun-alt

1. Created get all book function.
2. Created add book function.
3. Created update book function.
4. Created delete book function.
5. Created borrow book function to store the borrowed book that has been approved.
6. Created lend approval function for user to create lend book request.
7. Created admin lend approval function for admin to give approval and create notes for user if necessary.
8. Created return book function that takes username and book id as the request.
9. Created get history function for borrowed book, lend book request, returned book functions that takes user id as the parameter.

2022-09-13 02:05 UTC, gnumi34 requested changes
Bisa diperhatikan lagi

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/books/controller/http/httpbook.go
> +func NewBooksHTTPHandler(appGroup *echo.Group, uc books.Usecase) {
endpoint yang diakses oleh umum seperti GetAllBooks boleh nggak dikasih middleware Auth, tapi untuk endpoint yang diproteksi seperti AddBook, UpdateBook, DeleteBook, BorrowBook, dsb dikasih middleware Auth ya

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/books/repository/db/repository.go
> +		Select("*").
hindari penggunaan SELECT * karena akan mengurangi performa, tulis kolom yang di-SELECT satu-satu

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/books/repository/db/repository.go
> +		Unscoped().
Ini kenapa Unscoped() ya? Emang yang udah di-delete bisa dicari kembali?

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/books/service/books/usecase.go
> +	res, err := uc.DBRepo.LendApproval(ctx, req)
Ini kalau sama-sama Create dengan yang di AdminLendApproval, berarti akan ada 2 entry LendBook dengan buku yang sama dong?

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/books/service/books/usecase.go
> +	res, err := uc.DBRepo.LendApproval(ctx, req)
Harusnya ketika di-approve oleh Admin, kan tinggal di-update IsAccepted-nya jadi True

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/books/service/books/usecase.go
> +	if booksResult.Stock > booksResult.MaxStock {
kalau buku dikembalikan kayaknya ga mungkin kalau stok-nya lebih banyak dari max stock-nya. Coba dipikir, buku dikembalikan, kalau bukunya melebih maxStock masak bukunya jadi gabisa dikembaliin? mau diapain dong bukunya?

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/domain/books/models.go
> +	BookID      uint           `gorm:"autoIncrement:true, primaryKey, column:book_id" json:"book_id"`
di penulisan tag, pemisahannya pakai `;`, bukan `, `
```suggestion
	BookID      uint           `gorm:"autoIncrement:true;primaryKey;column:book_id" json:"book_id"`
```

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/domain/books/models.go
> +	Created_At  time.Time      `gorm:"autoCreateTime:true, column:created_at" json:"created_at"`
```suggestion
	Created_At  time.Time      `gorm:"autoCreateTime:true;column:created_at" json:"created_at"`
```

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/domain/books/models.go
> +	ID         uint              `gorm:"autoIncrement:true, primaryKey, column:id" json:"ID"`
```suggestion
	ID         uint              `gorm:"autoIncrement:true;primaryKey;column:id" json:"ID"`
```

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/domain/books/models.go
> +	BookID     uint              `gorm:"foreignKey:BookID, column:book_id" json:"book_id"`
```suggestion
	BookID     uint              `gorm:"foreignKey:BookID;column:book_id" json:"book_id"`
```

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/domain/books/models.go
> +	UserID     uint              `gorm:"foreignKey:UserID, column:user_id" json:"user_id"`
```suggestion
	UserID     uint              `gorm:"foreignKey:UserID;column:user_id" json:"user_id"`
```

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/domain/books/models.go
> +	BorrowedAt time.Time         `gorm:"autoCreateTime:true, column:borrowed_at" json:"borrowed_at"`
```suggestion
	BorrowedAt time.Time         `gorm:"autoCreateTime:true;column:borrowed_at" json:"borrowed_at"`
```

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/domain/books/models.go
> +	ID          uint      `gorm:"autoIncrement:true, primaryKey, column:id" json:"ID"`
```suggestion
	ID          uint      `gorm:"autoIncrement:true;primaryKey;column:id" json:"ID"`
```

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/domain/books/models.go
> +	RequestedAt time.Time `gorm:"autoCreateTime:true, column:requested_at" json:"requested_at"`
```suggestion
	RequestedAt time.Time `gorm:"autoCreateTime:true;column:requested_at" json:"requested_at"`
```

2022-09-13 02:05 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/helper/errcode/code.go
> +	if errors.Is(thisError, ErrNotFound) {
kalau if-condition panjang begini (lebih dari 2 kondisi) biasakan pakai `switch`.
```go
switch {
case errors.Is(thisError, ErrNotFound):
		return http.StatusNotFound, ErrNotFound
}
```
https://yourbasic.org/golang/switch-statement/

2022-09-13 02:38 UTC, Asgun-alt commented on project-1/Asgun-alt/pkg/books/repository/db/repository.go
> +		Unscoped().
kalau ga pakai unscoped nanti kolom deleted at nya  does not exist

2022-09-13 02:49 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/books/repository/db/repository.go
> +		Unscoped().
Woo iya saya baru nyadar, semua models yang disimpan di DB harus ditambahin created_at, updated_at, dan deleted_at ya.

2022-09-13 07:30 UTC, gnumi34 requested changes
masih ada yg kurang

2022-09-13 07:30 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/helper/errcode/code.go
> +	switch {
yang diubah ke `switch` jangan ini doang dong, yang lain juga

2022-09-13 10:02 UTC, Asgun-alt commented on project-1/Asgun-alt/pkg/books/repository/db/repository.go
> +		Unscoped().
ok siap mas

2022-09-14 02:35 UTC, gnumi34 approved these changes
LGTM

2022-09-14 02:35 UTC, merged