Asep gunawan
gnumi34/golang-mentoring pull request #3
Opened 2022-08-05 02:48 UTC by Asgun-alt

Finished step 1 of the project.

2022-08-05 05:48 UTC, gnumi34 requested changes
1. Struktur Clean Architecture-nya kurang tepat.
Harusnya handler/controller, usecase, repository dikelompokkan menjadi satu ke masing-masing module aplikasi, misal module `user`, ya di dalamnya dimasukkan controller, usecase, repository.
Referensi: https://github.com/gnumi34/word-counter

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/.env
> +DB_HOST = localhost
file config berisi credentials jangan di push ke repository

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/migration/users.sql
> +	user_id VARCHAR(40),
bikin primary key di dalam tabel ini. misal jadikan `user_id` sebagai primary key.

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/domain/base_response.go
> +func SuccessDataResponse(c echo.Context, data interface{}) error {
common response seperti ini jangan ditaruh di dalam `domain`, buatlah suatu base controller yang berisi method-method ini. Base controller tersebut di-embed ke dalam controller yang digunakan.

misal:
```go
type UserController struct {
    BaseController
    usecase uservice.UsersUsecaseInterface
}
```

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/controllers/usersctrl/httpuser.go
> +package usersctrl
nama package nya jangan seperti ini

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/controllers/usersctrl/httpuser.go
> +func (controller *UserController) GetUser(c echo.Context) error {
`controller` nya kepanjangan, biasanya cuma `(c *UserController)`

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/controllers/usersctrl/httpuser.go
> +	if validate.MustNotBeEmpty(req.Username) || validate.MustNotBeEmpty(req.Email) {
Next time nanti bisa digunakan module validator terpisah, jangan buat sendiri dari awal.
Referensi:
https://echo.labstack.com/guide/request/#validate-data

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/controllers/usersctrl/httpuser.go
> +func (controller *UserController) AddUsers(c echo.Context) error {
karena `user` yang dapat dimasukkan jumlahnya tunggal, nama fungsi juga harus tunggal, sehingga `AddUser`

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/controllers/usersctrl/httpuser.go
> +func (controller *UserController) UpdateUsers(c echo.Context) error {
Ikutin review di atas

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/controllers/usersctrl/httpuser.go
> +func (controller *UserController) DeleteUsers(c echo.Context) error {
Ini nanti ikuti review di atas

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/repository/database.go
> +func DbMigrate(db *gorm.DB) {
Fungsi ini nanti hilangkan ya, jangan pakai AutoMigrate-nya GORM

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/repository/database.go
> +package repository
init DB jangan ditaruh di dalam repository, taruhlah di helpers atau di dalam cmd

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/repository/users/record.go
> +type Users struct {
ini dijadikan satu aja dengan yang ada di domain, kurangi overhead.

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/repository/users/record.go
> +func (user *Users) ToUserDomain() uservice.UsersDomain {
dan ini harusnya nggak usah ada lagi

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase.go
> +	ctx  time.Duration
ini buat apa ya? kenapa time.Duration tapi namanya ctx?

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase.go
> +	if updateDomain.ID == "" {
ini kan udah divalidasi di awal, harusnya di use case gaperlu ada validasi lagi

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase.go
> +	users, result := usecase.repo.AddUsers(ctx, userDomain)
variabel error jangan dinamain `result`

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase.go
> +	users, result := usecase.repo.UpdateUsers(ctx, updateDomain)
variabel error jangan dinamain `result`

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase.go
> +	if result != nil {
variabel error jangan dinamain `result`

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase.go
> +	if (users.Created_At == time.Time{} && users.Email == "") {
Ini buat apa ya? Harusnya ngga perlu ada lagi

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase_test.go
> +	userRepository.On("GetUser",
1. karena ini mock ke repository, jangan pakai `mock.Anything` & `mock.AnythingOfType`, kan bisa di assign pake yang di assign ke userService.GetUser?
```go
t.Run("test case 1 | valid user", func(t *testing.T) {
	ctx := context.Background()
	req := uservice.UsersDomain{
		Username: "test-username",
		Password: "Test-password1",
	}
	userRepository.On("GetUser", ctx, req).Return(userDomain, nil).Once()
	user, err := userService.GetUser(context.Background(), uservice.UsersDomain{
		Username: "test-username",
		Password: "Test-password1",
	})
	assert.Nil(t, err)
	assert.Equal(t, "test-username", user.Username)
})
```
2. taruh mock ke dalam t.Run()-nya, jangan di luar. Kalau nanti case-nya lebih dari satu dan ada yang lebih dari 1 kali pemanggilan repository gimana?

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase_test.go
> +		userRepository.On("AddUsers",
1. karena ini mock ke repository, jangan pakai `mock.Anything` & `mock.AnythingOfType`, kan bisa di assign pake yang di assign ke userService.GetUser?
2. taruh mock ke dalam t.Run()-nya, jangan di luar. Kalau nanti case-nya lebih dari satu dan ada yang lebih dari 1 kali pemanggilan repository gimana?

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase_test.go
> +		userRepository.On("AddUsers",
1. karena ini mock ke repository, jangan pakai `mock.Anything` & `mock.AnythingOfType`, kan bisa di assign pake yang di assign ke userService.GetUser?
2. taruh mock ke dalam t.Run()-nya, jangan di luar. Kalau nanti case-nya lebih dari satu dan ada yang lebih dari 1 kali pemanggilan repository gimana?

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase_test.go
> +		userRepository.On("UpdateUsers",
1. karena ini mock ke repository, jangan pakai `mock.Anything` & `mock.AnythingOfType`, kan bisa di assign pake yang di assign ke userService.GetUser?
2. taruh mock ke dalam t.Run()-nya, jangan di luar. Kalau nanti case-nya lebih dari satu dan ada yang lebih dari 1 kali pemanggilan repository gimana?

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase_test.go
> +		userRepository.On("DeleteUsers",
1. karena ini mock ke repository, jangan pakai `mock.Anything` & `mock.AnythingOfType`, kan bisa di assign pake yang di assign ke userService.GetUser?

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase_test.go
> +		userRepository.On("DeleteUsers",
1. karena ini mock ke repository, jangan pakai `mock.Anything` & `mock.AnythingOfType`, kan bisa di assign pake yang di assign ke userService.GetUser?

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/user_domain.go
> +	DeleteUsers(CTX context.Context, id string) error
ctx-nya kecil aja

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/user_domain.go
> +	DeleteUsers(CTX context.Context, id string) error
ctx-nya kecil aja

2022-08-05 05:48 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/service/uservice/usecase.go
> +package uservice
ini nama package-nya jangan gini dong, yaudah aja `users`. Nanti kan pemanggilannya `service/users`. Nanti kalau bentrok, bisa di-override nama import-nya.
```go
import userService "github.com/gnumi34/golang-mentoring/tree/main/project-1/Asgun-alt/pkg/service/users" // kalau bentrok
```

2022-08-05 06:06 UTC, merged

2022-08-11 01:28 UTC, Asgun-alt commented on project-1/Asgun-alt/pkg/service/uservice/usecase_test.go
> +	userRepository.On("GetUser",
kalau pemanggilan repository nya lebih dari 1 goroutinenya error.
saya coba fix.