adding jwt authentication feature
gnumi34/golang-mentoring pull request #9
Opened 2022-08-19 09:34 UTC by Asgun-alt

2022-08-19 15:18 UTC, gnumi34 requested changes
1. Middleware jangan ditaruh di Controller. Taruhlah pada saat inisiasi router. https://echo.labstack.com/middleware/
2. Perhatikan separasi kode antar layer delivery, use case, dan repository.
Delivery untuk terima request, validasi request, sanitasi request, melempar dan menerima proses data dari use case, dan mengirim response ke client.
Use Case berisi business logic utama dari data request hasil validasi dan sanitasi pada controller, dan juga melakukan CRUD data pada sumber data eksternal dari layer repository bila diperlukan.
Repository berisi logic CRUD ke sumber data eksternal, tidak boleh ada business logic utama di sini.

2022-08-19 15:18 UTC, gnumi34 commented on project-1/Asgun-alt/.gitignore
> -vendor/*
folder vendor jangan dimasukkan ke dalam repo Github. Harus tetap di-ignore.

2022-08-19 15:18 UTC, gnumi34 commented on project-1/Asgun-alt/app/middlewares/auth.go
> +	ExpiresDuration int
```suggestion
	ExpireDuration int
```

2022-08-19 15:18 UTC, gnumi34 commented on project-1/Asgun-alt/app/middlewares/auth.go
> +	tokenPayload := &JWTCustomClaims{}
ini jangan cuma diextract payload dari token JWT-nya, tapi perlu divalidasi juga signature-nya apakah betul ini JWT datang dengan secret key yang anda tentukan sebelumnya. Hal ini membuat siapapun bisa mengakses sistem anda dong hanya dengan membuat token JWT yang payload-nya sesuai dengan yang anda susun?

2022-08-19 15:18 UTC, gnumi34 commented on project-1/Asgun-alt/cmd/main.go
> +func init() {
jangan biasakan menggunakan fungsi init() di package `main`.

2022-08-19 15:18 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/user/service/users/usecase.go
> +func NewUserUseCase(userRepo UsersRepositoryInterface, configJWT *middlewares.ConfigJWT) UsersUsecaseInterface {
config dari JWT kenapa ditaruh di layer UseCase ya?

2022-08-19 15:18 UTC, gnumi34 commented on project-1/Asgun-alt/config.json
> +        "expired": 24
file config jangan di push ke Repo Github, apalagi berisi kredensial seperti ini.

2022-08-19 15:18 UTC, gnumi34 commented on project-1/Asgun-alt/cmd/main.go
> +	usersUseCaseInterface := userUseCase.NewUserUseCase(usersRepoInterface, &configJWT)
config JWT ditaruh di useCase buat apa?

2022-08-19 15:18 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/user/controllers/users/httpuser.go
> +	token, err := middlewares.ValidateAuthorization(c)
Ini kenapa dipanggil di sini controller? Bukannya sudah dilakukan di middleware ya dengan memasang middleware di e.Get()?

2022-08-19 15:18 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/user/repository/users/db_user_repo.go
> +	match := encrypt.CheckPassword(userDomain.Password, user.Password)
Ini dilakukan di layer Use Case.

2022-08-19 15:18 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/user/repository/users/db_user_repo.go
> +	match := encrypt.CheckPassword(userDomain.Password, user.Password)
ini dilakukan di layer Use Case.

2022-08-19 15:18 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/user/service/users/usecase.go
> +	if userDomain.Username == "" {
Validasi jangan ditaruh di usecase, taruhlah di Controller.

2022-08-22 09:30 UTC, Asgun-alt commented on project-1/Asgun-alt/pkg/user/service/users/usecase.go
> +func NewUserUseCase(userRepo UsersRepositoryInterface, configJWT *middlewares.ConfigJWT) UsersUsecaseInterface {
ok mas, saya perbaharui lagi, tadinya di ke usecase seperti itu dan validasi signature jwt nya di folder jwt.
tapi saya perbaiki lagi usecasenya dengan cek langsung signed tokennya sesuai dengan secret key.

2022-09-02 07:32 UTC, gnumi34 approved these changes

2022-09-02 07:32 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/domain/books/repository.go
> +	BorrowedBook(ctx context.Context, domain *BorrowedBook) (*BorrowedBook, error)
Masih ada yang kurang untuk lihat list history catatan peminjaman buku & catatan yang lain yang diperlukan

2022-09-02 07:32 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/domain/books/usecase.go
> +	BorrowedBook(ctx context.Context, domain *BorrowedBook) (*BorrowedBook, error)
Belum ada use case untuk lihat history catatan peminjaman buku & catatan yg lain

2022-09-02 07:32 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/user/repository/users/db_user_repo.go
> +	match := encrypt.CheckPassword(userDomain.Password, user.Password)
ini kenapa masih dilakukan di repository? kan sudah dibilang dilakukan di use case?

2022-09-02 07:32 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/user/service/users/usecase.go
> +func NewUserUseCase(userRepo UsersRepositoryInterface, configJWT *middlewares.ConfigJWT) UsersUsecaseInterface {
ini configJWT masih dipakai di usecase nggak? hilangkan aja

2022-09-02 07:32 UTC, gnumi34 commented on project-1/Asgun-alt/pkg/user/service/users/usecase.go
> +	match := encrypt.CheckPassword(userDomain.Password, user.Password)
ini karena di repo udah ada checkPassword, jadi dilakukan 2 kali lo

2022-09-02 07:33 UTC, merged